def func(detectornormal,thetas,phis,As):
    
    seps = angle between detector normal and [theta,phi], where both are expressed in cartesian coord. 
    As = array of all possible strengths that it could be
    
    return response, which is As*cos^.76(seps). 
   

now to fit this with the data:
    
    
    
    

chi = func()


def chisquare(chi,data):
    data = the induced # of counts in the detector
    
    calculate chi squared:
    
    (chi-data)**2/data
    
    must find a way to resolve data being one value, while chi is a huge array
    
    
    



Next is identify the minimum value of this chisquare function, and figure out how to backtrack to see which theta, phi, and A's are associated with it. 

In [56]:
def copier(array,n):
    """Given an array input, return copies of it? 
    """

In [57]:
import healpy as hp
import numpy as np

In [58]:
hp.ang2vec([0,np.pi],[np.pi,0])

array([[ -0.00000000e+00,   0.00000000e+00,   1.00000000e+00],
       [  1.22464680e-16,   0.00000000e+00,  -1.00000000e+00]])

In [59]:
hp.ang2vec(np.pi,0)

array([  1.22464680e-16,   0.00000000e+00,  -1.00000000e+00])

In [60]:
thetas = np.linspace(0,90,10)
phis = np.linspace(0,360,37)

In [61]:
xx,yy = np.meshgrid(phis,thetas)

In [62]:
len(xx)

10

In [63]:
allphis = np.concatenate(xx)
allthetas = np.concatenate(yy)

allvecs = hp.ang2vec(np.deg2rad(allthetas),np.deg2rad(allphis))

In [55]:
allvecs[369]

array([  1.00000000e+00,  -2.44929360e-16,   6.12323400e-17])

In [65]:
allphis

array([   0.,   10.,   20.,   30.,   40.,   50.,   60.,   70.,   80.,
         90.,  100.,  110.,  120.,  130.,  140.,  150.,  160.,  170.,
        180.,  190.,  200.,  210.,  220.,  230.,  240.,  250.,  260.,
        270.,  280.,  290.,  300.,  310.,  320.,  330.,  340.,  350.,
        360.,    0.,   10.,   20.,   30.,   40.,   50.,   60.,   70.,
         80.,   90.,  100.,  110.,  120.,  130.,  140.,  150.,  160.,
        170.,  180.,  190.,  200.,  210.,  220.,  230.,  240.,  250.,
        260.,  270.,  280.,  290.,  300.,  310.,  320.,  330.,  340.,
        350.,  360.,    0.,   10.,   20.,   30.,   40.,   50.,   60.,
         70.,   80.,   90.,  100.,  110.,  120.,  130.,  140.,  150.,
        160.,  170.,  180.,  190.,  200.,  210.,  220.,  230.,  240.,
        250.,  260.,  270.,  280.,  290.,  300.,  310.,  320.,  330.,
        340.,  350.,  360.,    0.,   10.,   20.,   30.,   40.,   50.,
         60.,   70.,   80.,   90.,  100.,  110.,  120.,  130.,  140.,
        150.,  160.,

In [43]:
phis

array([   0.,   10.,   20.,   30.,   40.,   50.,   60.,   70.,   80.,
         90.,  100.,  110.,  120.,  130.,  140.,  150.,  160.,  170.,
        180.,  190.,  200.,  210.,  220.,  230.,  240.,  250.,  260.,
        270.,  280.,  290.,  300.,  310.,  320.,  330.,  340.,  350.,  360.])

In [44]:
allphis

array([   0.,   10.,   20.,   30.,   40.,   50.,   60.,   70.,   80.,
         90.,  100.,  110.,  120.,  130.,  140.,  150.,  160.,  170.,
        180.,  190.,  200.,  210.,  220.,  230.,  240.,  250.,  260.,
        270.,  280.,  290.,  300.,  310.,  320.,  330.,  340.,  350.,
        360.,    0.,   10.,   20.,   30.,   40.,   50.,   60.,   70.,
         80.,   90.,  100.,  110.,  120.,  130.,  140.,  150.,  160.,
        170.,  180.,  190.,  200.,  210.,  220.,  230.,  240.,  250.,
        260.,  270.,  280.,  290.,  300.,  310.,  320.,  330.,  340.,
        350.,  360.,    0.,   10.,   20.,   30.,   40.,   50.,   60.,
         70.,   80.,   90.,  100.,  110.,  120.,  130.,  140.,  150.,
        160.,  170.,  180.,  190.,  200.,  210.,  220.,  230.,  240.,
        250.,  260.,  270.,  280.,  290.,  300.,  310.,  320.,  330.,
        340.,  350.,  360.,    0.,   10.,   20.,   30.,   40.,   50.,
         60.,   70.,   80.,   90.,  100.,  110.,  120.,  130.,  140.,
        150.,  160.,

In [24]:
allthetas

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90.,   0.,
        10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90.,   0.,  10.,
        20.,  30.,  40.,  50.,  60.,  70.,  80.,  90.,   0.,  10.,  20.,
        30.,  40.,  50.,  60.,  70.,  80.,  90.,   0.,  10.,  20.,  30.,
        40.,  50.,  60.,  70.,  80.,  90.,   0.,  10.,  20.,  30.,  40.,
        50.,  60.,  70.,  80.,  90.,   0.,  10.,  20.,  30.,  40.,  50.,
        60.,  70.,  80.,  90.,   0.,  10.,  20.,  30.,  40.,  50.,  60.,
        70.,  80.,  90.,   0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,
        80.,  90.,   0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,
        90.,   0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90.,
         0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90.,   0.,
        10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90.,   0.,  10.,
        20.,  30.,  40.,  50.,  60.,  70.,  80.,  90.,   0.,  10.,  20.,
        30.,  40.,  50.,  60.,  70.,  80.,  90.,   