In [3]:
import burstsim as bs
import healpy as hp

In [4]:
cube1 = bs.BurstCube()


Are the detectors alternating? no
Please enter the tilt (deg) 34


In [6]:
#after making the cube, now it is time to pair it with a burst.

burst1 = bs.GRB(100,0,0)
burst1.print_details()

This GRB will produce an effect of 100 counts, located at polar angle 0.0 deg and azimuthal angle 0.0 deg.


In [7]:
cube1.detA

[0.59341194567807209, 0]

In [9]:

Anorm = hp.ang2vec(cube1.detA[0],cube1.detA[1])
Bnorm = hp.ang2vec(cube1.detB[0],cube1.detB[1])
Cnorm = hp.ang2vec(cube1.detC[0],cube1.detC[1])
Dnorm = hp.ang2vec(cube1.detD[0],cube1.detD[1])


Made an array of all the detector's normals, produce a certain number of counts using response.

In [14]:
pixels = hp.nside2npix(1)

In [15]:
pixels

12

In [25]:
class GRBs():
	"""
	Generates an array of GRB's given 
	certains strength at different sky positions.
	
	Output should be an array. 
	"""
	def __init__(self,NSIDE):
		#depending on NSIDE, there will be anywhere from 12 to infinite spots on the sky w/ GRBs

		self.pixels = hp.nside2npix(NSIDE)

		#want to convert these pixels into theta phi coords. 
		self.sourceangs = []
		for i in range(self.pixels):
			self.sourceangs.append(hp.pix2ang(NSIDE,i))



In [26]:
GRB = GRBs(2)

In [27]:
GRB.sourceangs

[(0.41113786232234778, 0.78539816339744828),
 (0.41113786232234778, 2.3561944901923448),
 (0.41113786232234778, 3.9269908169872414),
 (0.41113786232234778, 5.497787143782138),
 (0.84106867056793033, 0.39269908169872414),
 (0.84106867056793033, 1.1780972450961724),
 (0.84106867056793033, 1.9634954084936205),
 (0.84106867056793033, 2.748893571891069),
 (0.84106867056793033, 3.5342917352885168),
 (0.84106867056793033, 4.3196898986859651),
 (0.84106867056793033, 5.1050880620834134),
 (0.84106867056793033, 5.8904862254808616),
 (1.2309594173407747, 0.0),
 (1.2309594173407747, 0.78539816339744828),
 (1.2309594173407747, 1.5707963267948966),
 (1.2309594173407747, 2.3561944901923448),
 (1.2309594173407747, 3.1415926535897931),
 (1.2309594173407747, 3.926990816987241),
 (1.2309594173407747, 4.7123889803846897),
 (1.2309594173407747, 5.497787143782138),
 (1.5707963267948966, 0.39269908169872414),
 (1.5707963267948966, 1.1780972450961724),
 (1.5707963267948966, 1.9634954084936205),
 (1.5707963267

In [24]:
GRB.sourceangs[0]

(0.41113786232234778, 0.78539816339744828)

In [42]:
zenith = [0,0]
background = 1000
class BurstCube:
    import numpy as np
    import healpy as hp
    def __init__(self):
        test = input("Are the detectors alternating? ")
        if test == "yes" or test == "Yes" or test == "y" or test == "asdlfkjawe":           
            self.tiltA = np.deg2rad(float(input("Please enter the first tilt (deg) ")))
            self.tiltB = np.deg2rad(float(input("Please enter the second tilt (deg) ")))
            self.tiltC = self.tiltA
            self.tiltD = self.tiltD
        else:
            self.tilt = np.deg2rad(float(input("Please enter the tilt (deg) ")))
            self.tiltA = self.tiltB = self.tiltC = self.tiltD = self.tilt
            
    
    #make the normal vectors!
        #self.detA = [ zenith[0] + self.tiltA , zenith[1] ] 
        self.detB = [ zenith[0] + self.tiltB , zenith[1] + np.pi/2 ] 
        self.detC = [ zenith[0] + self.tiltC , zenith[1] + np.pi ] 
        self.detD = [ zenith[0] + self.tiltD , zenith[1] + 3*np.pi/2 ] 

        self.Anorm = hp.ang2vec(self.detA[0],self.detA[1])
        self.Bnorm = hp.ang2vec(self.detB[0],self.detB[1])
        self.Cnorm = hp.ang2vec(self.detC[0],self.detC[1])
        self.Dnorm = hp.ang2vec(self.detD[0],self.detD[1])

    
        self.dets = [self.Anorm,self.Bnorm,self.Cnorm,self.Dnorm] 
        
    @property
    def detA(self):
        return [ zenith[0] + self.tiltA , zenith[1] ]
    @property 
    def detB(self):
        return [ zenith[0] + self.tiltB , zenith[1] + np.pi/2 ]
    
    
    def respond2GRB(self, GRB):
        
        #do things to GRB
        
        return GRB
        

In [43]:
cube1 =  BurstCube()

Are the detectors alternating? y
Please enter the first tilt (deg) 45
Please enter the second tilt (deg) 45


AttributeError: 'BurstCube' object has no attribute 'tiltD'

In [41]:
cube1.respondToGRB(GRB)


#do individual responses to each GRB, this is from my localization stuff, and then I'm in business. 

[0.78539816339744828, 0]

In [37]:
cube1.dets

[array([ 0.5591929 ,  0.        ,  0.82903757]),
 array([  3.42406900e-17,   5.59192903e-01,   8.29037573e-01]),
 array([ -5.59192903e-01,   6.84813799e-17,   8.29037573e-01]),
 array([ -1.02722070e-16,  -5.59192903e-01,   8.29037573e-01])]